#!/usr/bin/env bash

# atom
alias e="atom-beta ."

# bundler
alias b="bundle"
alias bl="b --local"
alias bu="b update"
alias be="b exec"

# git
alias g='hub'
__git_complete g _git # enable bash completion for the `g` alias
alias gl='git pull --prune'
alias gp='git push'
alias gd='git diff'
alias gdh='git diff HEAD'
alias gap="git add -p"
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gcap='git commit -v -a && git push'
alias gb='git branch'
alias gba='git branch -a'
alias gs='git status'
alias grm="git status | grep deleted | awk '{print \$3}' | xargs git rm"
alias gco='git branch | cut -c 3- | selecta | xargs git checkout'
alias git-recent-branches='for k in `git branch|perl -pe s/^..//`;do echo -e `git show --pretty=format:"%Cgreen%ci %Cblue%cr%Creset" $k|head -n 1`\\t$k;done|sort -r'
alias grb='git-recent-branches'
alias gpr='git-pr'

# ls
alias l='ls -alh'
alias ltr='ls -ltrh'

# tail
alias tf='tail -f -n 100'
alias t500='tail -n 500'
alias t1000='tail -n 1000'
alias t2000='tail -n 2000'

# rails
alias rs='script/rails server'
alias rc='script/rails console'
alias rg='script/rails generate'
alias rdfl='rake db:fixtures:load'
alias rdm='rake db:migrate'
alias rst='touch tmp/restart.txt'

# misc
alias c=cd
alias reload='. ~/.bash_profile'
alias tmux="TERM=screen-256color-bce tmux"
alias h?="history | grep "
alias top-10-shell-commands="history | cut -c8- | cut -d' ' -f1 | sort | uniq -c | sort -nr | head"
alias brewup="echo_and_run brew update && echo_and_run brew cleanup && echo_and_run brew outdated && echo_and_run brew doctor"

# ip addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"

# kill stuff to fix camera detection in Zoom video conferencing
alias kill-camera="sudo killall VDCAssistant"
